theme: jekyll-theme-cayman
#remote_theme : "poole/hyde"

title:            'cosmo0 retro software'
tagline:          ''
description:      ''
url:              https://cosmo0.github.io/
baseurl:          /

author:
  name:           'cosmo0'
  url:            https://twitter.com/cosmoschtroumpf

github:
  repo:           https://github.com/cosmo0/